config/routes.rb
Rails.application.routes.draw do
  root to: "cocktails#index"
  # resources :cocktails, only: [:index, :show, :new, :create] do
  #   resources :doses, only: [:create]
  #   resources :reviews, only: [:create]
  # end
  # resources :doses, only: [:destroy]

  get "/cocktails",                           to: "cocktails#index"
  get "/cocktails/new",                       to: "cocktails#new",  as: "new_cocktail"
  get "/cocktails/:id",                       to: "cocktails#show", as: "cocktail"
  post "/cocktails",                          to: "cocktails#create"
  # get "/cocktails/:cocktail_id/doses/",     to: "doses#new",      as: "new_cocktail_dose"
  post "/cocktails/:cocktail_id/doses/",      to: "doses#create",   as: "cocktail_doses"
  delete "/doses/:id",                        to: "doses#destroy",  as: "dose"
  post "/cocktails/:cocktail_id/reviews/",    to: "reviews#create", as: "cocktail_reviews"
  # no route needed via cocktails on this last one,
  # we can delete without knowing the cocktail ID
  # cause we already know the dose ID to destroy.
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews
  validates :name, uniqueness: true, presence: true, allow_blank: false
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true, allow_blank: false
  # validates_uniqueness_of :ingredient_id, scope: :cocktail_id
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, uniqueness: true, presence: true, allow_blank: false
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail # only one user
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new # cause it's used to render a Dose form on the Show page
    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
     if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
     # def new
     #  @cocktail = Cocktail.find(params[:cocktail_id])
     #  @dose = Dose.new
     # end

    def create
       @cocktail = Cocktail.find(params[:cocktail_id])
       @dose = Dose.new(dose_params)
       @dose.cocktail = @cocktail
       if @dose.save
        redirect_to cocktail_path(@cocktail)
      else
        render "cocktails/new"
      end
    end

    def destroy
      @dose = Dose.find(params[:id])
      @dose.destroy
      redirect_to cocktail_path(@dose.cocktail)
    end
  private

    def dose_params
      params.require(:dose).permit(:description, :ingredient_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      @dose = Dose.new #check why
      render "cocktails/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/index.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>cocktails</h1>
    <p>for drinking</p>
    <%= link_to "Add new cocktail", new_cocktail_path %>
  </div>

</div>

<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
       <div class="col-12 col-md-6 col-lg-3">
        <div id="cardscontainer">
          <% if cocktail.photo? %>
            <% background_url = cl_image_path cocktail.photo, width: 400, height: 500, crop: :fill %>
          <% else %>
            <% background_url = 'https://source.unsplash.com/500x400/?cocktail' %>
          <% end %>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= background_url %>');">
            <div class="card-description">
              <h2><%= cocktail.name %></h2>
            </div>
            <%= link_to "", cocktail_path(cocktail), class: 'card-link' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
 <h1>Create a new cocktail</h1>

  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>

app/views/cocktails/show.html.erb
<div>
  <h1><%= @cocktail.name %></h1>
  <%= link_to "home", root_path %>
</div>
<%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>
<p>
  <% @cocktail.doses.each do |dose| %>
  <p> <%= dose.ingredient.name %> - <%= dose.description %> - <%= link_to "(delete)", dose_path(dose), method: :delete%></p>
  <% end %>
</p>
 <%= render "doses/new", cocktail: @cocktail, dose: @dose %>
 <%= render "reviews/new", cocktail: @cocktail, review: @review %>
  <% if @cocktail.reviews.empty? %>
    <p>Be the first to let a review</p>
  <% else %>
    <% @cocktail.reviews.each do |review| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <span class="badge badge-primary badge-pill">
          <% counter = 0 %>
          <% 5.times do %>
            <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
            <% counter += 1 %>
          <% end %>
        </span>
        <%= review.content %>
      </li>
    <% end %>
  <% end %>

app/views/doses/_new.html.erb
<%= simple_form_for [cocktail, dose] do |f| %>  <!-- NOT for @cocktail! then it doesn't find :ingredient -->
  <%= f.association :ingredient %>
  <%= f.input :description %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/reviews/_new.html.erb
<h3>Add a review</h3>
<%= simple_form_for [cocktail, review] do |f| %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.input :content %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>